version: '3'

services:
    postgres-db:
        image: postgres
        container_name: postgres-db
        environment:
            - POSTGRES_USER=devtools_user
            - POSTGRES_PASSWORD=DevTools1!
            - POSTGRES_DB=devtools_db
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data

    sql-server-db:
        image: microsoft/mssql-server-linux
        container_name: sql-server-db
        environment:
            - SA_PASSWORD=c3kgC5#Adfl*
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
        ports:
            - "1433:1433"
