version: '3'

services:
    postgres-db:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=psql-db
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
